apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
w      nodePort: 30000
  selector:
    app: primeiro-pod
#sรณ funciona em plataformas, para ter um ip exertno tem que criar um service node
